### PR TITLE
Get binlog file and position from master rather than having it hardcoded

### PR DESCRIPTION
**Pull request by hhorak**
In case the slave gets `REPLICATION CLIENT` permissions (imho it's fine) it can get master status and so we don't have to hard-code binlog file and position in the code, which is imho wrong approach.

### CODE REVIEW

**Comment by mfojtik** [comment]
ok to test

@hhorak I added you to the admin list in Jenkins so all your PR's should be tested automatically.

**Comment by mfojtik** [comment]
[test] ?

**Comment by bparees** [comment]
@hhorak i'm going to close this so you can re-open it and hopefully trigger the jenkins test.

**Comment by mfojtik** [comment]
I tested this manually and it works :-)

**Comment by mfojtik** [comment]
[test] to test jenkins :)

**Comment by bparees** [comment]
jenkins ignores your plea for attention.

**Comment by mfojtik** [comment]
[test]

now with updated plugin.

**Comment by mfojtik** [comment]
test

**Comment by mfojtik** [comment]
omg omg @bparees it worked :-)

**Pull request merged**
