### PR TITLE
Fix replication

### PR DESCRIPTION
**Pull request by mnagy**
Start master properly, initializing correct configuration files. This will fix the replication for 5.5

@bparees @mfojtik @hhorak @soltysh @pmorie @smarterclayton

### CODE REVIEW

**Comment by bparees** [comment]
lgtm, waiting for test pass.

**Comment by bparees** [comment]
@sdodson we're going to want to re-spin the mysql 5.5 image with this change if that's possible.

**Comment by hhorak** [comment]
lgtm

**Comment by hhorak** [comment]
btw. we're able to respin the 5.6, no problem with that..

**Pull request merged**
