### PR TITLE
5.x/test/run: misc shell improvements

### PR DESCRIPTION
**Pull request by php-coder**
- rewrite `mysql_cmd` function to not rely on the global variables
- use `local` keyword in more places

PTAL @mnagy @bparees

### CODE REVIEW

**Comment by bparees** [comment]
lgtm, needs squashing.

**Comment by bparees** [comment]
looks like repo issues. [test]

**Comment by php-coder** [comment]
[test]

**Comment by php-coder** [comment]
@bparees Squashed and ready for merge.

**Comment by bparees** [comment]
lgtm

**Pull request merged**
