### PR TITLE
workaround for squash rm issues

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@mfojtik ptal

**Comment by bparees** [comment]
@hhorak fyi

**Comment by mfojtik** [comment]
@bparees LGTM but still interested to hear from Marek what is the root cause of this

**Comment by mfojtik** [comment]
@bparees need extra step, this one breaks as well

**Comment by bparees** [comment]
@mfojtik thanks. updated.

**Pull request merged**
