### PR TITLE
Fix the mysql replication example

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees this just updates the template to adopt recent patterns. I tested this and it is working \o/

**Comment by mfojtik** [comment]
@jhadvig PTAAH

**Comment by jhadvig** [comment]
@mfojtik looking && testing...

**Comment by bparees** [comment]
@jhadvig testing successful?

**Comment by mfojtik** [comment]
I tested this and presented today :) Everything is working and you can
nicely scale this up or down... One thing that I think I should change is
the service name to be just mysql so you can use this template with our
examples.

**Comment by bparees** [comment]
you can use the template w/ our examples, our examples let you specify the DB service name now.

**Pull request merged**
