### PR TITLE
Verify all installed packages using rpm -V

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by bparees** [comment]
please work with @mnagy to figure out why our mysql tests seem really flaky.  they fail in the push job too.

**Comment by mnagy** [comment]
@bparees @mfojtik this particular failure looks to be related to the PR:
```
The command '/bin/sh -c yum install -y centos-release-scl &&     INSTALL_PKGS="install gettext hostname bind-utils rh-mysql56" &&     yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all &&     mkdir -p /var/lib/mysql/data && chown -R mysql.0 /var/lib/mysql &&     test "$(id mysql)" = "uid=27(mysql) gid=27(mysql) groups=27(mysql)"' returned a non-zero code: 1
make: *** [test] Error 1
+ echo 'ERROR: mysql-centos7 failed testing.'
```
I'll look into the pusher job.

**Comment by mfojtik** [comment]
@mnagy that is my typo, "install" is not valid package...

**Comment by mnagy** [comment]
@mfojtik will you change this to -q?

**Comment by mfojtik** [comment]
@mnagy maybe in future :-)

**Pull request merged**
