### PR TITLE
Unify MySQL logging statements across versions

### PR DESCRIPTION
**Pull request by mnagy**
The log_volume_info is now at the beginning and at the end as well.

### CODE REVIEW

**Comment by mnagy** [comment]
[test]

**Comment by mnagy** [comment]
@rhcarvalho

**Comment by rhcarvalho** [comment]
Thanks @mnagy! Running late now, I will take a closer look later, you know diff of diffs :yum:

**Comment by rhcarvalho** [comment]
@mnagy LGTM, thanks! I check the diff and now the differences left are explained by @hhorak in #140.

I think you have merge powers here, right?

**Comment by bparees** [comment]
thanks @mnagy

**Pull request merged**
