### PR TITLE
Remove trap in ./hack/build.sh

### PR DESCRIPTION
**Pull request by mfojtik**
https://github.com/openshift/sti-base/issues/43

### CODE REVIEW

**Comment by bparees** [comment]
if you're going to do this, let's rename them to Dockerfile.centos7 too.

**Comment by bparees** [comment]
though to do that you're going to have to fix up vagrant too.

**Comment by mfojtik** [comment]
@bparees would prefer to have at least one 'Dockerfile' in repo ;-) So if you just do docker build it works without having to specify extra parameters or use `make build`.

**Comment by bparees** [comment]
@mfojtik i guess.  could symlink dockerfile->dockerfile.centos7 :)

**Pull request merged**
