### PR TITLE
Reduce innodb_buffer_pool_size for replication test

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@bparees FYI

**Comment by mnagy** [comment]
Can you please add the "$@" args to `start_local_mysql` for the invocation in `contrib/common.sh` and `run-mysqld.sh`? Both for 5.5 and 5.6. And careful not to pass `$1` as well, which could be `mysqld`.

**Comment by mfojtik** [comment]
@mnagy should be fixed now.

**Comment by mnagy** [comment]
Great! :) LGTM

**Comment by rhcarvalho** [comment]
Validating @mnagy's effort in having better tests for replication, this PR introduced a bug fixed 4 days later in https://github.com/openshift/mysql/pull/78.

@bparees FYI

**Pull request merged**
