### PR TITLE
Removed last references to osc command

### PR DESCRIPTION
**Pull request by oscerd**
Hi,

This PR just remove the remaining references to osc command.

Andrea

### CODE REVIEW

**Comment by bparees** [comment]
ok to test

**Comment by mfojtik** [comment]
[test]

**Comment by bparees** [comment]
@mfojtik clearly we still don't have this working for non-whitelisted folks :)

**Comment by bparees** [comment]
seems safe enough to me.
thanks for the catch, @oscerd!

**Comment by mfojtik** [comment]
@bparees was worth trying :) I will try to fix jenkins for all repos tomorrow.

**Pull request merged**
